#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /testdir/clone ensure=absent force=true
puppet resource file /testdir ensure=directory
puppet resource file /testdir/clone ensure=directory
cd /testdir/clone
git clone https://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@github.com/bcsim-git/devops_repo.git
cp -p /testdir/clone/devops_repo/index.html /var/www/html
