#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /testdir/clone ensure=absent force=true
puppet resource file /testdir ensure=directory
puppet resource file /testdir/clone ensure=directory
cd /21051233/script_dir
git clone https://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@github.com/siiiyiiing/operate_repo.git
cp -p /21051233/script_dir/operate_repo/index.html /var/www/html
